### ISSUE TITLE
provide nuget packages and update to net8/latest avalonia

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [sandreas/Avalonia.SimpleRouter#1]
provide nuget packages and update to net8/latest avalonia

**Comment by sandreas** [comment]
Acutally, there already is a nuget package:

https://www.nuget.org/packages/Sandreas.Avalonia.SimpleRouter

And there is also no dependency to Avalonia at all, in fact there is only one small dependency to 
```
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
```
to provide one single "feature": A shorter way of wiring the IoC container. Therefore I plan to eleminate it for `v0.0.4`, because this way I won't need to bump dependencies in any future version and can concentrate on fixing bugs on this really small lib.

Keeping support for `net6.0` as a long term release would be good in my opinion to provide LTS. Is there any advantage having .net8.0 (e.g. `AOT` or something)?

**Comment by sandreas** [comment]
Closed due to no further feedback.

**Comment by cesarchefinho** [comment]
> Acutally, there already is a nuget package:
> 
> https://www.nuget.org/packages/Sandreas.Avalonia.SimpleRouter
> 
> And there is also no dependency to Avalonia at all, in fact there is only one small dependency to
> 
> ```
> <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
> ```
> 
> to provide one single "feature": A shorter way of wiring the IoC container. Therefore I plan to eleminate it for `v0.0.4`, because this way I won't need to bump dependencies in any future version and can concentrate on fixing bugs on this really small lib.
> 
> Keeping support for `net6.0` as a long term release would be good in my opinion to provide LTS. Is there any advantage having .net8.0 (e.g. `AOT` or something)?

sorry for delay.

Net8 drop support for some things inside ne6, specialy between net8-android and net6-android. Consuming net6 library has problems.

If we can get an official net8 package or an net standart2.0 package is bether for this situation.

**Comment by sandreas** [comment]
> Net8 drop support for some things inside ne6, specialy between net8-android and net6-android. Consuming net6 library has problems.

Ok... I'll do some research. Thanks for pointing this out but I would love to understand which problems there are and how they come up...

Here is an explanatory reddit task for understanding the differences (for my research):
https://www.reddit.com/r/csharp/comments/v0g5ds/is_net_6_backwards_compatible_with_net_standard/
